const en = {
  translation: {
    nav: {
      title: 'PG Manager',
      notifications: 'Notifications',
      unread: '{{count}} unread',
      loading: 'Loading…',
      close: 'Close',
      none: 'No notifications',
      refresh: 'Refresh',
      more: 'More',
      profile: 'Your Profile',
      settings: 'Settings',
      sign_out: 'Sign out',
      user: 'User',
      filter_by_buildings: 'Filter by buildings',
      all_buildings: 'All Buildings',
      n_selected: '{{count}} selected',
      select_all: 'Select All',
      clear: 'Clear',
    },
    sidebar: {
      dashboard: 'Dashboard',
      buildings: 'Buildings',
      tenants: 'Tenants',
      income: 'Income',
      expenses: 'Expenses',
      bookings: 'Bookings',
      payments: 'Payments',
      messages: 'Messages',
      settings: 'Settings',
      reports: 'Reports',
      staffs: 'Staffs'
    },
    login: {
      login_as: 'Login As',
      select_role: 'Select Role',
      role_pg_admin: 'PG Admin',
      role_pg_staff: 'PG Staff',
      email: 'Email Address',
      email_placeholder: 'Enter your email',
      password: 'Password',
      password_placeholder: 'Enter your password',
      remember_me: 'Remember me',
      forgot_password: 'Forgot password?',
      sign_in: 'Sign In',
      signing_in: 'Signing in...',
      no_account: "Don't have an account?",
      sign_up: 'Sign up',
      success: 'Login successful! Redirecting...',
      errors: {
        select_role: 'Please select a role',
        email_required: 'Email is required',
        email_invalid: 'Email is invalid',
        password_required: 'Password is required',
        failed: 'Login failed. Please check your credentials and try again.'
      }
    },
    buildings: {
      title: 'Buildings',
      add_building: 'Add Building',
      edit_building_title: 'Edit Building: {{name}}',
      name: 'Name',
      city: 'City',
      state: 'State',
      type: 'Type',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      actions: 'Actions',
      list: 'List',
      cards: 'Cards',
      no_buildings: 'No buildings found',
      loading: 'Loading buildings...',
      permission_denied: 'You do not have permission to view any buildings',
      load_failed: 'Failed to load buildings',
      view_details: 'View details',
      address: 'Address:',
      notes: 'Notes:',
      address_label: 'Address',
      notes_label: 'Notes',
      overview: 'Overview',
      back: 'Back',
      view_on_maps: 'View on Maps',
      open_in_maps: 'Open in Google Maps',
      floors_label: 'Floors',
      rooms_label: 'Rooms',
      beds_label: 'Beds',
      code: 'Code',
      pincode: 'Pincode',
      manager: 'Manager',
      created: 'Created',
      updated: 'Updated',
      not_found: 'Building not found.',
      updated_success: 'Building updated',
      property_type: 'Property Type',
      total_tenants: 'Total Tenants',
      pg_capacity: 'PG Capacity',
      room_occupancy: 'Room Occupancy',
      bed_occupancy: 'Bed Occupancy',
      tooltip_occupied: '{{pct}}% occupied',
      tooltip_available: '{{pct}}% available',
      tooltip_maintenance: '{{pct}}% maintenance',
      available: 'Available',
      occupied: 'Occupied',
      reserved: 'Reserved',
      maintenance_short: 'Maint.',
      type_boys: 'Boys',
      type_girls: 'Girls',
      type_coliving: 'Co-living',
      building_with_id: 'Building {{id}}',
      action_edit: 'Edit',
      action_inactive_soft_deleted: 'Inactive (Soft Deleted)',
      action_soft_delete: 'Soft Delete',
      action_delete_permanently: 'Delete Permanently',
      confirm_delete_title: 'Delete Building',
      confirm_soft_delete_title: 'Soft Delete Building',
      confirm_delete_message: 'This will permanently delete "{{name}}". This action cannot be undone.',
      confirm_soft_delete_message: 'Mark "{{name}}" as inactive? You can restore it later by setting Active to true.',
      cancel: 'Cancel',
      soft_delete: 'Soft Delete',
      delete_hold_shift: 'Delete (Hold Shift)',
      permission_edit_deny: 'You do not have permission to edit this building.',
      permission_delete_deny: 'You do not have permission to delete this building.',
      toasts_marked_inactive: 'Building marked inactive',
      toasts_soft_delete_failed: 'Soft delete failed',
      toasts_deleted_permanently: 'Building deleted permanently',
      toasts_delete_failed: 'Delete failed',
      toasts_hold_shift_to_confirm: 'Hold Shift and click Delete to confirm permanent deletion',
      stats_loading: 'Loading stats…',
      stats_load_failed: 'Failed to load stats',
      placeholders: {
        name: 'Enter building name',
        address: 'Enter address',
        city: 'Enter city',
        state: 'Enter state',
        pincode: '6 digits',
        code: 'Optional',
        notes: 'Any additional information...'
      },
      errors: {
        owner_required: 'Owner is required',
        name_required: 'Name is required',
        address_required: 'Address is required',
        city_required: 'City is required',
        state_required: 'State is required',
        pincode_invalid: 'Pincode must be exactly 6 digits',
        please_fix_fields: 'Please fix the highlighted fields'
      },
      permissions: {
        no_permission_edit_buildings: 'You do not have permission to edit buildings',
        no_permission_add_buildings: 'You do not have permission to add buildings',
        permission_denied_cannot_edit_building: 'Permission denied: cannot edit this building.',
        permission_denied_cannot_add_buildings: 'Permission denied: cannot add buildings.'
      },
      update: 'Update',
      toasts: {
        building_updated: 'Building updated: {{name}}',
        building_created: 'Building created: {{name}}'
      },
      inactive_actions_blocked: 'This building is inactive. Activate it to make changes.',
      plan_limit_reached_cannot_add: 'Plan limit reached: cannot add more buildings. Upgrade plan or deactivate an existing building.'
    },
    floors: {
      floor: 'Floor',
      floors: 'Floors',
      building: 'Building',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      notes: 'Notes',
      actions: 'Actions',
      list: 'List',
      cards: 'Cards',
      overview: 'Overview',
      no_floors: 'No floors found',
      no_floors_for_building: 'No floors found for this building',
      loading: 'Loading floors...',
      permission_denied: 'You do not have permission to view floors',
      permission_denied_for_building: 'You do not have permission to view floors for this building',
      load_failed: 'Failed to load floors',
      view_details: 'View details',
      rooms: 'Rooms',
      beds: 'Beds',
      capacity: 'Capacity',
      room_occupancy: 'Room Occupancy',
      bed_occupancy: 'Bed Occupancy',
      tooltip_occupied: '{{pct}}% occupied',
      tooltip_available: '{{pct}}% available',
      action_edit: 'Edit',
      action_inactive_soft_deleted: 'Inactive (Soft Deleted)',
      action_soft_delete: 'Soft Delete',
      action_delete_permanently: 'Delete Permanently',
      confirm_delete_title: 'Delete Floor',
      confirm_soft_delete_title: 'Soft Delete Floor',
      confirm_delete_message: 'This will permanently delete "{{name}}". This action cannot be undone.',
      confirm_delete_alt_inactive_hint: 'Tip: Instead of deleting, you can mark this floor inactive from Edit.',
      confirm_soft_delete_message: 'Mark "{{name}}" as inactive? You can restore it later by setting Active to true.',
      cancel: 'Cancel',
      soft_delete: 'Soft Delete',
      delete_hold_shift: 'Delete (Hold Shift)',
      toasts_marked_inactive: 'Floor marked inactive',
      toasts_soft_delete_failed: 'Soft delete failed',
      toasts_deleted_permanently: 'Floor deleted permanently',
      toasts_delete_failed: 'Delete failed',
      toasts_hold_shift_to_confirm: 'Hold Shift and click Delete to confirm permanent deletion',
      tooltip_soft_delete_blocked_occupied_rooms: 'Cannot soft delete: {{count}} occupied room(s) on this floor',
      tooltip_delete_blocked_occupied_rooms: 'Cannot delete: {{count}} occupied room(s) on this floor',
      toasts_soft_delete_blocked_occupied_rooms: 'Cannot soft delete floor. {{count}} room(s) are occupied.',
      toasts_delete_blocked_occupied_rooms: 'Cannot delete floor. {{count}} room(s) are occupied.',
      tooltip_soft_delete_blocked_unknown_occupancy: 'Cannot soft delete: occupancy cannot be verified for this floor',
      tooltip_delete_blocked_unknown_occupancy: 'Cannot delete: occupancy cannot be verified for this floor',
      toasts_soft_delete_blocked_unknown_occupancy: 'Cannot soft delete floor because occupancy cannot be verified.',
      toasts_delete_blocked_unknown_occupancy: 'Cannot delete floor because occupancy cannot be verified.',
      floor_label_ground: 'Ground Floor',
      floor_label_suffix: 'Floor',
      titles: {
        title: 'Floors',
        add_floor: 'Add Floor',
        edit_floor_title: 'Edit Floor: {{name}}',
        edit_floor: 'Edit Floor'
      },
      floor_label_unknown: '-',
      placeholders: {
        select_building: 'Select building',
        select_floor: 'Select floor'
      },
      errors: {
        building_required: 'Building is required',
        number_required: 'Number is required',
        number_numeric: 'Number must be numeric',
        number_range: 'Number must be between 0 and 14',
        duplicate_for_building: 'This floor already exists for the selected building.'
      },
      permissions: {
        reason_edit: "You don't have permission to edit floors for this building.",
        reason_add: "You don't have permission to add floors.",
        deny_edit: 'Permission denied: cannot edit floors for this building.',
        deny_add: 'Permission denied: cannot add floors.',
        deny_delete: 'Permission denied: cannot delete floors for this building.'
      },
      buttons: {
        save_changes: 'Save Changes',
        create_floor: 'Create Floor'
      },
      toasts: {
        floor_updated: 'Floor updated: {{name}}',
        floor_created: 'Floor created: {{name}}',
        created_success: 'Floor created',
        updated_success: 'Floor updated'
      },
      save_failed: 'Failed to save floor'
    },
    rooms: {
      room: 'Room',
      rooms: 'Rooms',
      floor: 'Floor',
      type: 'Type',
      capacity: 'Capacity',
      bed_occupancy: 'Bed Occupancy',
      rent: 'Rent',
      deposit: 'Deposit',
      available: 'Available',
      occupied: 'Occupied',
      reserved: 'Reserved',
      maintenance: 'Maintenance',
      yes: 'Yes',
      no: 'No',
      actions: 'Actions',
      list: 'List',
      cards: 'Cards',
      view_details: 'View details',
      no_rooms: 'No rooms found',
      no_rooms_for_floor: 'No rooms found for this floor',
      loading: 'Loading rooms...',
      permission_denied: 'You do not have permission to view rooms',
      load_failed: 'Failed to load rooms',
      titles: {
        title: 'Rooms',
        add_room: 'Add Room',
        edit_room_title: 'Edit Room: {{name}}',
        edit_room: 'Edit Room'
      },
      labels: {
        number: 'Room Number',
        room_type: 'Room Type',
        monthly_rent: 'Monthly Rent',
        security_deposit: 'Security Deposit',
        notes: 'Notes',
        active: 'Active',
        beds: 'Beds',
        bed_number: 'Bed Number',
        auto_number: 'Auto-number 1..N'
      },
      types: {
        single_sharing: 'Single Sharing',
        n_sharing: '{{n}} Sharing'
      },
      errors: {
        floor_required: 'Floor is required',
        number_required: 'Room number is required',
        room_type_required: 'Room type is required',
        monthly_rent_required: 'Monthly rent is required',
        security_deposit_required: 'Security deposit is required',
        capacity_required: 'Capacity is required',
        bed_number_required: 'Each bed must have a number',
        bed_number_unique: 'Bed numbers must be unique',
        number_duplicate: 'This room number already exists on the selected floor.'
      },
      permissions: {
        reason_edit: "You don't have permission to edit rooms for this building.",
        reason_add: "You don't have permission to add rooms.",
        deny_edit: 'Permission denied: cannot edit rooms for this building.',
        deny_add: 'Permission denied: cannot add rooms.',
        deny_delete: 'Permission denied: cannot delete rooms for this building.',
        reason_delete: "You don't have permission to delete rooms."
      },
      action_edit: 'Edit',
      action_inactive_soft_deleted: 'Inactive (Soft Deleted)',
      action_soft_delete: 'Soft Delete',
      action_delete_permanently: 'Delete Permanently',
      confirm_delete_title: 'Delete Room',
      confirm_soft_delete_title: 'Soft Delete Room',
      confirm_delete_message: 'This will permanently delete "{{name}}". This action cannot be undone.',
      confirm_delete_alt_inactive_hint: 'Tip: Instead of deleting, you can mark this room inactive from Edit.',
      confirm_soft_delete_message: 'Mark "{{name}}" as inactive? You can restore it later by setting Active to true.',
      cancel: 'Cancel',
      soft_delete: 'Soft Delete',
      delete_hold_shift: 'Delete (Hold Shift)',
      tooltip_delete_blocked_occupied_beds: 'Cannot delete: {{count}} occupied bed(s) in this room',
      tooltip_delete_blocked_unknown_occupancy: 'Cannot delete: occupancy cannot be verified for this room',
      toasts_delete_blocked_occupied_beds: 'Cannot delete room. {{count}} bed(s) are occupied.',
      toasts_delete_blocked_unknown_occupancy: 'Cannot delete room because occupancy cannot be verified.',
      buttons: {
        save_changes: 'Save Changes',
        create_room: 'Create Room'
      },
      toasts: {
        created_success: 'Room created',
        updated_success: 'Room updated',
        marked_inactive: 'Room marked inactive',
        soft_delete_failed: 'Soft delete failed',
        deleted_permanently: 'Room deleted permanently',
        delete_failed: 'Delete failed',
        hold_shift_to_confirm: 'Hold Shift and click Delete to confirm permanent deletion'
      },
      save_failed: 'Failed to save room',
      room_hash_n: 'Room #{{n}}',
      search_placeholder: 'Search room by number',
      checking_capacity: 'Checking capacity…',
      capacity_summary: 'Capacity: {{capacity}} • Existing beds: {{count}}'
    },
    beds: {
      title: 'Beds',
      bed: 'Bed',
      beds: 'Beds',
      loading: 'Loading beds...',
      no_beds: 'No beds found',
      no_beds_for_room: 'No beds found for this room',
      view_details: 'View details',
      bed_with_number: 'Bed {{n}}',
      number: 'Bed Number',
      auto_number: 'Auto-number 1..N',
      available: 'Available',
      occupied: 'Occupied',
      maintenance: 'Maintenance',
      reserved: 'Reserved',
      rent: 'Rent',
      monthly_rent: 'Monthly Rent',
      notes: 'Notes',
      status: 'Status',
      room: 'Room',
      building: 'Building',
      floor: 'Floor',
      tenant: 'Tenant',
      no_tenant: 'No Tenant',
      confirm_delete: 'Are you sure you want to delete this bed?',
      delete_success: 'Bed deleted successfully',
      delete_error: 'Error deleting bed',
      save_success: 'Bed saved successfully',
      save_error: 'Error saving bed',
      number_placeholder: 'e.g., B1, 1, A-01',
      rent_placeholder: 'e.g., 3500.00',
      notes_placeholder_maintenance: 'Reason for maintenance (required)',
      notes_placeholder_optional: 'Optional notes',
      history: {
        title_for_label: 'Bed History for {{label}}',
        description: 'Recent stays and bookings for this bed',
        occupied_no_history_hint: 'Bed is marked as Occupied due to a Booking, but there is no Stay history yet. Create a Stay to track bed usage history.',
        no_history: 'No history found'
      },
      actions: {
        add_bed: 'Add Bed',
        edit_bed: 'Edit Bed',
        delete_bed: 'Delete Bed',
        create_bed: 'Create Bed',
        check_out: 'Check-out',
        confirm_checkout: 'Confirm Check-out'
      },
      dialogs: {
        delete_title: 'Delete Bed',
        checkout_title: 'Check-out Tenant',
        delete_description: 'This will permanently delete "{{label}}". This action cannot be undone.',
        checkout_description: 'Proceed to check-out current tenant from "{{label}}"? This will set today\'s date as actual checkout.'
      },
      confirm_delete_alt_inactive_hint: 'Tip: Instead of deleting, you can mark this bed inactive from Edit.',
      tooltip_delete_blocked_occupied: 'Cannot delete: this bed is occupied',
      tooltip_delete_blocked_unknown_occupancy: 'Cannot delete: occupancy cannot be verified for this bed',
      toasts_delete_blocked_occupied: 'Cannot delete bed because it is occupied.',
      toasts_delete_blocked_unknown_occupancy: 'Cannot delete bed because occupancy cannot be verified.',
      toasts: {
        created: 'Bed created successfully',
        updated: 'Bed updated successfully',
        updated_success: 'Bed updated successfully',
        checked_out_success: 'Tenant checked out successfully',
        deleted_permanently: 'Bed deleted permanently'
      },
      errors: {
        checkout_failed: 'Checkout failed',
        delete_failed: 'Delete failed',
        save_failed: 'Failed to save bed',
        load_failed: 'Failed to load beds'
      },
      validation: {
        number_required: 'Bed number is required',
        number_unique: 'This bed number already exists',
        room_required: 'Room is required',
        room_at_capacity: 'Cannot add more beds. Room capacity is {{capacity}} and it already has {{count}} bed(s).',
        maintenance_reason_required: 'Please provide a reason when setting status to maintenance.',
        rent_non_negative: 'Monthly rent must be a non-negative number'
      },
      statuses: {
        available: 'Available',
        occupied: 'Occupied',
        maintenance: 'Maintenance',
        reserved: 'Reserved'
      },
      columns: {
        number: 'Bed #',
        status: 'Status',
        rent: 'Rent'
      }
    },
    settings: {
      page: {
        title: 'Settings',
        subtitle: 'Manage your account and app preferences',
      },
      tabs: {
        notifications: 'Notifications',
        localization: 'Localization',
        invoices: 'Invoices',
        language: 'Language',
      },
      language: {
        title: 'Language',
        subtitle: 'Choose your preferred app language.',
        label: 'Language',
        current: 'Current',
      },
      localization: {
        title: 'Localization',
        subtitle: 'Regional settings for dates, times and timezone.',
        admin_only: 'Only PG Admins can modify these settings. You have read-only access.',
        timezone: 'Timezone',
        date_format: 'Date format',
        time_format: 'Time format',
        loading: 'Loading…',
        save: 'Save',
        saving: 'Saving…',
        confirm_title: 'Confirm Save',
        confirm_message: 'Are you sure you want to save these localization settings?',
        cancel: 'Cancel',
        confirm: 'Confirm',
        saved_success: 'Localization settings saved.',
        save_failed: 'Failed to save localization settings.',
      },
      notifications: {
        title: 'Notifications',
        subtitle: 'Choose how you want to be notified.',
        channels: {
          email: 'Email notifications',
          sms: 'SMS notifications',
          push: 'Push notifications',
        },
        save_prefs: 'Save Preferences',
        saved_success: 'Notification preferences saved.',
        save_failed: 'Failed to save notification preferences.',
      }
    },
    common: {
      save: 'Save',
      saving: 'Saving…',
      success: 'Success',
      load_more: 'Load more',
      retry: 'Retry',
      actions: 'Actions',
      edit: 'Edit',
      delete_permanently: 'Delete Permanently',
      cancel: 'Cancel',
      confirm: 'Confirm',
      delete_hold_shift: 'Delete (Hold Shift)',
      hold_shift_to_confirm: 'Hold Shift and click Delete to confirm permanent deletion',
      date_ranges: {
        today: 'Today',
        yesterday: 'Yesterday',
        last7: 'Last 7 days',
        last15: 'Last 15 days',
        last30: 'Last 30 days',
        this_month: 'This month',
        last_month: 'Last month',
        this_year: 'This year',
        last_year: 'Last year',
        range: 'Range'
      }
    },
    toasts: {
      must_login: 'You must be logged in to update language.',
      language_saved: 'Language preference saved.',
      save_failed: 'Failed to save language.',
    },
    notifications: {
      title: 'Notifications',
      subtitle: 'Recent account activity and system alerts',
      tabs: { unread: 'Unread', read: 'Read', all: 'All' },
      ip: 'IP',
      mark_all_read: 'Mark all as read',
      marked_all_read: 'All notifications marked as read.',
      empty_title: 'You’re all caught up',
      empty_subtitle: 'No notifications yet. Activity will show up here.',
      load_failed: 'Failed to load notifications.',
      sections: {
        today: 'Today',
        yesterday: 'Yesterday',
        earlier: 'Earlier'
      },
      time: {
        just_now: 'just now',
        m_ago: '{{count}}m ago',
        h_ago: '{{count}}h ago',
        yesterday: 'yesterday'
      }
    },
    dashboard: {
      bed_availability: {
        title: 'Bed availability',
        view_all: 'View all',
        search_placeholder: 'Search bed, room, building...',
        available_beds: 'Available beds',
        loading: 'Loading…',
        empty: 'No available beds found for the selection.',
        bed_fallback: 'Bed #{{id}}',
        room: 'Room',
        building: 'Building',
        available_badge: 'Available',
        view_more: 'View {{count}} more →'
      },
      cashflow: {
        title: 'Cashflow',
        tabs: {
          overview: 'Overview',
          expenses: 'Expenses',
          weekdays: 'Weekdays'
        },
        error: {
          title: 'Failed to load',
          retry: 'Retry'
        },
        charts: {
          income_vs_expenses: 'Income vs Expenses'
        },
        series: {
          income: 'Income',
          expenses: 'Expenses'
        },
        kpis: {
          title: 'Key Metrics',
          total_income: 'Total Income',
          total_expenses: 'Total Expenses',
          average_net: 'Average Net'
        },
        expenses: {
          category_share: 'Category Share'
        },
        table: {
          category: 'Category',
          amount: 'Amount',
          percentage: 'Percentage',
          total: 'Total'
        },
        weekdays: {
          title: 'Income vs Expenses by Weekday'
        }
      },
      bookings_trend: {
        title: 'Bookings',
        tabs: { overview: 'Overview', sources: 'Sources', trends: 'Trends' },
        status_distribution: 'Status Distribution',
        count: 'Count',
        key_metrics: 'Key Metrics',
        total_bookings: 'Total Bookings',
        total_revenue: 'Total Revenue',
        booking_rate: 'Booking Rate',
        cancellation_rate: 'Cancellation Rate',
        booking_sources_rate: 'Booking Sources Rate',
        source_details: 'Source Details',
        source: 'Source',
        bookings: 'Bookings',
        bookings_short: 'bookings',
        conv_short: 'conv',
        conversion_rate: 'Conversion Rate',
        market_share: 'Market Share',
        daily_booking_pattern: 'Daily Booking Pattern',
        daily_bookings: 'Daily Bookings'
      },
      tenant_snapshot: {
        title: 'Tenant Snapshot',
        view_all: 'View all',
        total_tenants: 'Total Tenants',
        upcoming_checkins: 'Upcoming Check-ins',
        upcoming_checkouts: 'Upcoming Check-outs',
        selected_buildings: 'Selected Buildings',
        recent_tenants: 'Recent Tenants',
        open: 'Open',
        no_tenants: 'No tenants found.',
        view_more: 'View more'
      },
      occupancy: {
        title: 'Live occupancy',
        occupied_chip: 'occupied',
        buildings_label: 'Buildings',
        all: 'All',
        beds_considered: 'Beds considered',
        empty: 'No beds found for the selected buildings. Adjust the filter to view occupancy.',
        aria_overall: 'Overall occupancy',
        legend: {
          occupied: 'Occupied',
          reserved: 'Reserved',
          maintenance: 'Maintenance',
          available: 'Available'
        },
        stats: {
          total: 'Total',
          occupied: 'Occupied',
          reserved: 'Reserved',
          maintenance: 'Maintenance',
          available: 'Available',
          occupied_pct: 'Occupied',
          available_pct: 'Available'
        },
        beds_with_count: '{{count}} beds'
      },
      header: {
        greeting: { morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening' },
        subtitle: 'Your dashboard is ready.'
      }
    },
  }
};

export default { translation: en.translation };
