const mr = {
  translation: {
    nav: { title: 'PG व्यवस्थापक', notifications: 'सूचना', unread: '{{count}} न वाचलेले', loading: 'लोड होत आहे…', close: 'बंद करा', none: 'कोणतीही सूचना नाहीत', refresh: 'रीफ्रेश', more: 'अधिक', profile: 'तुमची प्रोफाइल', settings: 'सेटिंग्ज', sign_out: 'साइन आउट',
      user: 'वापरकर्ता',
      filter_by_buildings: 'इमारतीनुसार फिल्टर करा',
      all_buildings: 'सर्व इमारती',
      n_selected: '{{count}} निवडले',
      select_all: 'सर्व निवडा',
      clear: 'क्लियर' },
    sidebar: { dashboard: 'डॅशबोर्ड', buildings: 'इमारती', tenants: 'भाडेकरू', income: 'उत्पन्न', expenses: 'खर्चे', bookings: 'बुकिंग्स', payments: 'पेमेंट्स', messages: 'संदेश', settings: 'सेटिंग्ज', reports: 'अहवाल', staffs: 'स्टाफ' },
    login: { login_as: 'लॉगिन करा', select_role: 'भूमिका निवडा', role_pg_admin: 'PG अॅडमिन', role_pg_staff: 'PG स्टाफ', email: 'ईमेल पत्ता', email_placeholder: 'तुमचा ईमेल टाका', password: 'पासवर्ड', password_placeholder: 'तुमचा पासवर्ड टाका', remember_me: 'मला आठव', forgot_password: 'पासवर्ड विसरलात?', sign_in: 'साइन इन', signing_in: 'साइन इन होत आहे...', no_account: 'खाते नाही?', sign_up: 'साइन अप', success: 'लॉगिन यशस्वी! पुनर्निर्देशित करत आहोत...', errors: { select_role: 'कृपया भूमिका निवडा', email_required: 'ईमेल आवश्यक आहे', email_invalid: 'ईमेल अवैध आहे', password_required: 'पासवर्ड आवश्यक आहे', failed: 'लॉगिन अयशस्वी. कृपया तपासा आणि पुन्हा प्रयत्न करा.' } },
    buildings: { 
      name: 'नाव', 
      city: 'शहर', 
      state: 'राज्य', 
      type: 'प्रकार', 
      status: 'स्थिती', 
      active: 'सक्रिय', 
      inactive: 'निष्क्रिय', 
      actions: 'कृती', 
      list: 'यादी', 
      cards: 'कार्ड्स', 
      overview: 'आढावा',
      no_buildings: 'कोणतीही इमारत सापडली नाही', 
      no_buildings_for_building: 'या इमारतीसाठी कोणतीही इमारत सापडली नाही', 
      loading: 'इमारती लोड होत आहेत...', 
      permission_denied: 'आपल्याला कोणत्याही इमारती पाहण्याची परवानगी नाही', 
      permission_denied_for_building: 'आपल्याला या इमारतीचे इमारती पाहण्याची परवानगी नाही', 
      load_failed: 'इमारती लोड करण्यात अयशस्वी', 
      view_details: 'तपशील पहा', 
      address: 'पत्ता:', 
      notes: 'नोट्स:', 
      type_boys: 'मुलगे', 
      type_girls: 'मुली', 
      type_coliving: 'को-लिव्हिंग',
      building_with_id: 'इमारत {{id}}',
      title: 'इमारती',
      add_building: 'इमारत जोडा',
      edit_building_title: 'इमारत संपादा: {{name}}',
      address_label: 'पत्ता',
      notes_label: 'नोट्स',
      back: 'मागे',
      view_on_maps: 'नकाशावर पाहा',
      open_in_maps: 'Google Maps मध्ये उघडा',
      floors_label: 'मजले',
      rooms_label: 'खोली',
      beds_label: 'खाटा',
      code: 'कोड',
      pincode: 'पिनकोड',
      manager: 'व्यवस्थापक',
      created: 'निर्मित',
      updated: 'अद्यतनित',
      not_found: 'इमारत सापडली नाही.',
      updated_success: 'इमारत अद्यतनित',
      property_type: 'मालमत्तेचा प्रकार',
      total_tenants: 'एकूण भाडेकरू',
      pg_capacity: 'PG क्षमता',
      room_occupancy: 'खोली व्याप्ती',
      bed_occupancy: 'खाटा व्याप्ती',
      tooltip_occupied: '{{pct}}% व्याप्त',
      tooltip_available: '{{pct}}% उपलब्ध',
      tooltip_maintenance: '{{pct}}% देखभाल',
      available: 'उपलब्ध',
      occupied: 'व्याप्त',
      reserved: 'आरक्षित',
      maintenance_short: 'देखभाल',
      action_edit: 'संपादा',
      action_inactive_soft_deleted: 'निष्क्रिय (सॉफ्ट डिलीट)',
      action_soft_delete: 'सॉफ्ट डिलीट',
      action_delete_permanently: 'कायमचे हटवा',
      confirm_delete_title: 'इमारत हटवा',
      confirm_soft_delete_title: 'इमारत निष्क्रिय करा',
      confirm_delete_message: 'हे "{{name}}" कायमचे हटवेल. ही कृती मागे घेता येणार नाही.',
      confirm_soft_delete_message: '"{{name}}" निष्क्रिय करायचे? नंतर Active true करून पुनर्संचयित करू शकता.',
      cancel: 'रद्द',
      soft_delete: 'सॉफ्ट डिलीट',
      delete_hold_shift: 'हटवा (Shift धरून)',
      permission_edit_deny: 'आपल्याला ही इमारत संपादित करण्याची परवानगी नाही.',
      permission_delete_deny: 'आपल्याला ही इमारत हटवण्याची परवानगी नाही.',
      toasts_marked_inactive: 'इमारत निष्क्रिय केली',
      toasts_soft_delete_failed: 'सॉफ्ट डिलीट अयशस्वी',
      toasts_deleted_permanently: 'इमारत कायमची हटवली',
      toasts_delete_failed: 'हटवणे अयशस्वी',
      toasts_hold_shift_to_confirm: 'कायमचे हटवण्याची पुष्टीसाठी Shift धरून हटवा क्लिक करा',
      stats_loading: 'सांख्यिकी लोड होत आहे…',
      stats_load_failed: 'सांख्यिकी लोड करण्यात अयशस्वी',
      placeholders: { name: 'इमारतीचे नाव टाका', address: 'पत्ता टाका', city: 'शहर टाका', state: 'राज्य टाका', pincode: '6 अंक', code: 'ऐच्छिक', notes: 'अतिरिक्त माहिती...' },
      errors: { owner_required: 'मालक आवश्यक आहे', name_required: 'नाव आवश्यक आहे', address_required: 'पत्ता आवश्यक आहे', city_required: 'शहर आवश्यक आहे', state_required: 'राज्य आवश्यक आहे', pincode_invalid: 'पिनकोड नेमके 6 अंकांचा असावा', please_fix_fields: 'हायलाइट केलेली क्षेत्रे दुरुस्त करा' },
      permissions: { no_permission_edit_buildings: 'आपल्याला इमारती संपादित करण्याची परवानगी नाही', no_permission_add_buildings: 'आपल्याला इमारती जोडण्याची परवानगी नाही', permission_denied_cannot_edit_building: 'परवानगी नाकारली: ही इमारत संपादित करू शकत नाही.', permission_denied_cannot_add_buildings: 'परवानगी नाकारली: इमारती जोडू शकत नाही.' },
      update: 'अद्यतन',
      toasts: { building_updated: 'इमारत अद्यतनित: {{name}}', building_created: 'इमारत तयार: {{name}}' }
    },
    floors: {
      floor: 'मजला',
      floors: 'मजले',
      building: 'इमारत',
      notes: 'नोट्स',
      actions: 'कृती',
      list: 'यादी',
      cards: 'कार्ड्स',
      overview: 'आढावा',
      no_floors: 'कोणतेही मजले सापडले नाहीत',
      no_floors_for_building: 'या इमारतीसाठी कोणतेही मजले सापडले नाहीत',
      loading: 'मजले लोड होत आहेत...',
      permission_denied: 'आपल्याला मजले पाहण्याची परवानगी नाही',
      permission_denied_for_building: 'आपल्याला या इमारतीचे मजले पाहण्याची परवानगी नाही',
      load_failed: 'मजले लोड करण्यात अयशस्वी',
      view_details: 'तपशील पहा',
      rooms: 'खोल्या',
      beds: 'खाटा',
      capacity: 'क्षमता',
      room_occupancy: 'खोली व्याप्ती',
      bed_occupancy: 'खाटा व्याप्ती',
      tooltip_occupied: '{{pct}}% व्याप्त',
      tooltip_available: '{{pct}}% उपलब्ध',
      floor_label_unknown: '-',
      floor_label_ground: 'भूतल',
      floor_label_suffix: 'मजला',
      titles: {
        title: 'मजले',
        add_floor: 'मजला जोडा',
        edit_floor_title: 'मजला संपादा: {{name}}',
        edit_floor: 'मजला संपादा'
      },
      placeholders: {
        select_building: 'इमारत निवडा',
        select_floor: 'मजला निवडा'
      },
      errors: {
        building_required: 'इमारत आवश्यक आहे',
        number_required: 'क्रमांक आवश्यक आहे',
        number_numeric: 'क्रमांक अंकात्मक असावा',
        number_range: 'क्रमांक 0 ते 14 दरम्यान असावा',
        duplicate_for_building: 'निवडलेल्या इमारतीसाठी हा मजला आधीच अस्तित्वात आहे.'
      },
      permissions: {
        reason_edit: 'या इमारतीसाठी मजला संपादित करण्यास तुम्हाला परवानगी नाही.',
        reason_add: 'मजला जोडण्यास तुम्हाला परवानगी नाही.',
        deny_edit: 'परवानगी नाकारली: या इमारतीसाठी मजला संपादित करू शकत नाही.',
        deny_add: 'परवानगी नाकारली: मजला जोडू शकत नाही.',
        deny_delete: 'परवानगी नाकारली: या इमारतीसाठी मजला हटवू शकत नाही.'
      },
      buttons: {
        save_changes: 'बदल जतन करा',
        create_floor: 'मजला तयार करा'
      },
      toasts: {
        floor_updated: 'मजला अद्यतनित: {{name}}',
        floor_created: 'मजला तयार: {{name}}',
        created_success: 'मजला तयार',
        updated_success: 'मजला अद्यतनित'
      },
      save_failed: 'मजला जतन करण्यात अयशस्वी',
      action_edit: 'संपादा',
      action_inactive_soft_deleted: 'निष्क्रिय (सॉफ्ट डिलीट)',
      action_soft_delete: 'सॉफ्ट डिलीट',
      action_delete_permanently: 'कायमचे हटवा',
      confirm_delete_title: 'मजला हटवा',
      confirm_soft_delete_title: 'मजला निष्क्रिय करा',
      confirm_delete_message: 'हे "{{name}}" कायमचे हटवेल. ही कृती मागे घेता येणार नाही.',
      confirm_soft_delete_message: '"{{name}}" निष्क्रिय करायचे? नंतर Active true करून पुनर्संचयित करू शकता.',
      cancel: 'रद्द',
      soft_delete: 'सॉफ्ट डिलीट',
      delete_hold_shift: 'हटवा (Shift धरून)',
      toasts_marked_inactive: 'मजला निष्क्रिय केला',
      toasts_soft_delete_failed: 'सॉफ्ट डिलीट अयशस्वी',
      toasts_deleted_permanently: 'मजला कायमचा हटवला',
      toasts_delete_failed: 'हटवणे अयशस्वी',
      toasts_hold_shift_to_confirm: 'कायमचे हटवण्याची पुष्टीसाठी Shift धरून हटवा क्लिक करा'
    },
    rooms: {
      room: 'खोली',
      rooms: 'खोल्या',
      floor: 'मजला',
      type: 'प्रकार',
      capacity: 'क्षमता',
      rent: 'भाडे',
      deposit: 'डिपॉझिट',
      available: 'उपलब्ध',
      occupied: 'व्याप्त',
      reserved: 'आरक्षित',
      maintenance: 'देखभाल',
      yes: 'होय',
      no: 'नाही',
      actions: 'कृती',
      list: 'यादी',
      cards: 'कार्ड्स',
      no_rooms_for_floor: 'या मजल्यासाठी कोणत्याही खोल्या नाहीत',
      no_rooms: 'कोणत्याही खोल्या सापडल्या नाहीत',
      view_details: 'तपशील पहा',
      loading: 'खोल्या लोड होत आहेत...',
      permission_denied: 'आपल्याला खोल्या पाहण्याची परवानगी नाही',
      load_failed: 'खोल्या लोड करण्यात अयशस्वी',
      titles: {
        title: 'खोल्या',
        add_room: 'खोली जोडा',
        edit_room_title: 'खोली संपादा: {{name}}',
        edit_room: 'खोली संपादा'
      },
      labels: {
        number: 'खोली क्रमांक',
        room_type: 'खोली प्रकार',
        monthly_rent: 'मासिक भाडे',
        security_deposit: 'सिक्युरिटी डिपॉझिट',
        notes: 'नोट्स',
        active: 'सक्रिय',
        beds: 'खाटा',
        bed_number: 'खाट क्रमांक',
        status: 'स्थिती',
        auto_number: 'स्वयंक्रमांक'
      },
      types: {
        single_sharing: 'सिंगल शेअरिंग',
        n_sharing: '{{n}} शेअरिंग'
      },
      errors: {
        floor_required: 'मजला आवश्यक आहे',
        number_required: 'खोली क्रमांक आवश्यक आहे',
        room_type_required: 'खोली प्रकार आवश्यक आहे',
        capacity_required: 'क्षमता आवश्यक आहे',
        bed_number_required: 'प्रत्येक खाटेस क्रमांक आवश्यक आहे',
        bed_number_unique: 'खाट क्रमांक अद्वितीय असावेत',
        number_duplicate: 'खोली क्रमांक आधीच अस्तित्वात आहे'
      },
      permissions: {
        reason_edit: 'या इमारतीसाठी खोली संपादित करण्यास तुम्हाला परवानगी नाही.',
        reason_add: 'खोली जोडण्यास तुम्हाला परवानगी नाही.',
        reason_delete: 'या इमारतीसाठी खोली हटवण्यास तुम्हाला परवानगी नाही.',
        deny_edit: 'परवानगी नाकारली: या इमारतीसाठी खोली संपादित करू शकत नाही.',
        deny_add: 'परवानगी नाकारली: खोली जोडू शकत नाही.',
        deny_delete: 'परवानगी नाकारली: या इमारतीसाठी खोली हटवू शकत नाही.'
      },
      buttons: {
        save_changes: 'बदल जतन करा',
        create_room: 'खोली तयार करा'
      },
      toasts: {
        updated_success: 'खोली अद्यतनित',
        created_success: 'खोली तयार',
        marked_inactive: 'खोली निष्क्रिय केली',
        soft_delete_failed: 'सॉफ्ट डिलीट अयशस्वी',
        deleted_permanently: 'खोली कायमची हटवली',
        delete_failed: 'हटवणे अयशस्वी',
        hold_shift_to_confirm: 'कायमचे हटवण्याची पुष्टीसाठी Shift धरून हटवा क्लिक करा'
      },
      save_failed: 'खोली जतन करण्यात अयशस्वी',
      action_edit: 'संपादा',
      action_inactive_soft_deleted: 'निष्क्रिय (सॉफ्ट डिलीट)',
      action_soft_delete: 'सॉफ्ट डिलीट',
      action_delete_permanently: 'कायमचे हटवा',
      confirm_delete_title: 'खोली हटवा',
      confirm_soft_delete_title: 'खोली निष्क्रिय करा',
      confirm_delete_message: 'हे "{{name}}" कायमचे हटवेल. ही कृती मागे घेता येणार नाही.',
      confirm_soft_delete_message: '"{{name}}" निष्क्रिय करायचे? नंतर Active true करून पुनर्संचयित करू शकता.',
      cancel: 'रद्द',
      soft_delete: 'सॉफ्ट डिलीट',
      delete_hold_shift: 'हटवा (Shift धरून)'
    },
    beds: {
      title: 'बेड',
      bed: 'बेड',
      beds: 'बेड',
      loading: 'बेड लोड होत आहेत...',
      no_beds: 'कोणतेही बेड सापडले नाही',
      no_beds_for_room: 'या खोलीसाठी कोणतेही बेड सापडले नाही',
      view_details: 'तपशील पहा',
      bed_with_number: 'बेड {{n}}',
      number: 'बेड नंबर',
      auto_number: 'स्वयं-क्रमांक १..एन',
      available: 'उपलब्ध',
      occupied: 'व्यापलेले',
      maintenance: 'दुरुस्ती',
      reserved: 'राखीव',
      rent: 'भाडे',
      status: 'स्थिती',
      room: 'खोली',
      building: 'इमारत',
      floor: 'मजला',
      tenant: 'भाडेकरू',
      no_tenant: 'भाडेकरू नाही',
      notes: 'नोट्स',
      confirm_delete: 'तुम्हाला हे बेड नक्की हटवायचे आहे?',
      delete_success: 'बेड यशस्वीरित्या हटवले',
      delete_error: 'बेड हटवताना त्रुटी',
      save_success: 'बेड यशस्वीरित्या जतन केले',
      save_error: 'बेड जतन करताना त्रुटी',
      validation: {
        number_required: 'बेड नंबर आवश्यक आहे',
        number_unique: 'हा बेड नंबर आधीपासून अस्तित्वात आहे',
        room_required: 'खोली निवडणे आवश्यक आहे'
      },
      statuses: {
        available: 'उपलब्ध',
        occupied: 'व्यापलेले',
        maintenance: 'दुरुस्ती',
        reserved: 'राखीव'
      },
      columns: {
        number: 'बेड #',
        status: 'स्थिती',
        rent: 'भाडे'
      },
      toasts: {
        created: 'बेड यशस्वीरित्या तयार केले',
        updated: 'बेड यशस्वीरित्या अद्यतनित केले',
        updated_success: 'बेड यशस्वीरित्या अद्यतनित केले',
        checked_out_success: 'भाडेकरू यशस्वीरित्या चेक-आउट झाले',
        deleted_permanently: 'बेड कायमचे हटवले'
      },
      errors: {
        checkout_failed: 'चेक-आउट अयशस्वी',
        delete_failed: 'हटवणे अयशस्वी',
        save_failed: 'बेड जतन करण्यात अयशस्वी',
        load_failed: 'बेड लोड करण्यात अयशस्वी'
      },
      actions: {
        add_bed: 'बेड जोडा',
        edit_bed: 'बेड संपादित करा',
        delete_bed: 'बेड हटवा',
        create_bed: 'बेड तयार करा',
        check_out: 'चेक-आउट',
        confirm_checkout: 'चेक-आउटची पुष्टी करा'
      },
      dialogs: {
        delete_title: 'बेड हटवा',
        checkout_title: 'भाडेकरू चेक-आउट',
        delete_description: 'हे "{{label}}" कायमचे हटवेल. ही कृती मागे घेता येणार नाही.',
        checkout_description: 'सध्याच्या भाडेकरूचा "{{label}}" मधून चेक-आउट करायचा? आजची तारीख प्रत्यक्ष चेक-आउट म्हणून सेट केली जाईल.',
        number_placeholder: 'उदा, B1, 1, A-01',
        rent_placeholder: 'उदा, 3500.00',
        notes_placeholder_maintenance: 'देखभालीचे कारण (आवश्यक)',
        notes_placeholder_optional: 'पर्यायी नोट्स',
        notes_placeholder: 'अतिरिक्त माहिती...'
      },
      history: {
        title_for_label: '{{label}} साठी बेड इतिहास',
        description: 'या बेडसाठी अलीकडील मुक्काम आणि बुकिंग',
        occupied_no_history_hint: 'बुकिंगमुळे बेड व्यापलेले म्हणून चिन्हांकित केले आहे, परंतु अद्याप कोणताही मुक्काम इतिहास नाही. बेड वापराचा इतिहास ट्रॅक करण्यासाठी मुक्काम तयार करा.',
        no_history: 'कोणताही इतिहास सापडला नाही'
      }
    },
    settings: { 
      language: { title: 'भाषा', subtitle: 'तुमची आवडती अॅप भाषा निवडा.', label: 'भाषा', current: 'सद्य' },
      localization: { cancel: 'रद्द करा' }
    },
    common: {
      save: 'सेव्ह',
      saving: 'सेव्ह होत आहे…',
      load_more: 'आणखी लोड करा',
      actions: 'कृती',
      edit: 'संपादा',
      delete_permanently: 'कायमचे हटवा',
      cancel: 'रद्द',
      confirm: 'पुष्टी',
      delete_hold_shift: 'हटवा (Shift धरून)',
      hold_shift_to_confirm: 'कायमचे हटवण्याची पुष्टीसाठी Shift धरून हटवा क्लिक करा',
      date_ranges: {
        today: 'आज',
        yesterday: 'काल',
        last7: 'मागील 7 दिवस',
        last15: 'मागील 15 दिवस',
        last30: 'मागील 30 दिवस',
        this_month: 'हा महिना',
        last_month: 'मागील महिना',
        this_year: 'हे वर्ष',
        last_year: 'मागील वर्ष',
        range: 'रेंज'
      }
    },
    toasts: { must_login: 'भाषा अपडेट करण्यासाठी लॉगिन आवश्यक.', language_saved: 'भाषा प्राधान्य सेव्ह केले.', save_failed: 'भाषा सेव्ह करण्यात अयशस्वी.' },
    dashboard: {
      bed_availability: {
        title: 'बेड उपलब्धता',
        view_all: 'सर्व पहा',
        search_placeholder: 'बेड, रूम, बिल्डिंग शोधा...',
        available_beds: 'उपलब्ध बेड',
        loading: 'लोड होत आहे…',
        load_failed: 'लोड करण्यात अयशस्वी',
        empty: 'निवडीसाठी कोणतेही उपलब्ध बेड सापडले नाहीत.',
        bed_fallback: 'बेड #{{id}}',
        room: 'रूम',
        building: 'बिल्डिंग',
        available_badge: 'उपलब्ध',
        view_more: 'आणखी {{count}} पहा'
      },
      cashflow: {
        title: 'कॅशफ्लो',
        tabs: {
          overview: 'आढावा',
          expenses: 'खर्च',
          weekdays: 'आठवड्याचे दिवस'
        },
        error: {
          title: 'लोड करण्यात अयशस्वी',
          retry: 'पुन्हा प्रयत्न करा'
        },
        charts: {
          income_vs_expenses: 'उत्पन्न विरुद्ध खर्च'
        },
        series: {
          income: 'उत्पन्न',
          expenses: 'खर्च'
        },
        kpis: {
          title: 'मुख्य मेट्रिक्स',
          total_income: 'एकूण उत्पन्न',
          total_expenses: 'एकूण खर्च',
          average_net: 'सरासरी नेट'
        },
        expenses: {
          category_share: 'वर्गातील वाटा'
        },
        table: {
          category: 'वर्ग',
          amount: 'रक्कम',
          percentage: 'टक्केवारी',
          total: 'एकूण'
        },
        weekdays: {
          title: 'आठवड्याच्या दिवसांनुसार उत्पन्न विरुद्ध खर्च'
        }
      },
      bookings_trend: {
        title: 'बुकिंग्स',
        tabs: { overview: 'आढावा', sources: 'स्रोत', trends: 'कल' },
        status_distribution: 'स्थितीचे वितरण',
        count: 'संख्या',
        key_metrics: 'मुख्य निदर्शक',
        total_bookings: 'एकूण बुकिंग्स',
        total_revenue: 'एकूण महसूल',
        booking_rate: 'बुकिंग दर',
        cancellation_rate: 'रद्द दर',
        booking_sources_rate: 'बुकिंग स्रोतांचा दर',
        source_details: 'स्रोत तपशील',
        source: 'स्रोत',
        bookings: 'बुकिंग्स',
        bookings_short: 'बुकिंग्स',
        conv_short: 'कन्व',
        conversion_rate: 'रूपांतरण दर',
        market_share: 'बाजारातील हिस्सा',
        daily_booking_pattern: 'दैनिक बुकिंग नमुना',
        daily_bookings: 'दैनिक बुकिंग्स'
      },
      tenant_snapshot: {
        title: 'भाडेकरू सारांश',
        view_all: 'सर्व पहा',
        total_tenants: 'एकूण भाडेकरू',
        upcoming_checkins: 'येणारी चेक-इन',
        upcoming_checkouts: 'येणारी चेक-आउट',
        selected_buildings: 'निवडलेल्या इमारती',
        recent_tenants: 'अलीकडील भाडेकरू',
        open: 'उघडा',
        no_tenants: 'कोणतेही भाडेकरू आढळले नाहीत.',
        view_more: 'आणखी पहा'
      },
      occupancy: {
        title: 'थेट व्याप्ती',
        occupied_chip: 'व्याप्त',
        buildings_label: 'इमारती',
        all: 'सर्व',
        beds_considered: 'विचारातील खाटा',
        empty: 'निवडलेल्या इमारतींसाठी कोणत्याही खाटा सापडल्या नाहीत. व्याप्ती पाहण्यासाठी फिल्टर समायोजित करा.',
        aria_overall: 'एकूण व्याप्ती',
        legend: { occupied: 'व्याप्त', reserved: 'आरक्षित', maintenance: 'देखभाल', available: 'उपलब्ध' },
        stats: { total: 'एकूण', occupied: 'व्याप्त', reserved: 'आरक्षित', maintenance: 'देखभाल', available: 'उपलब्ध', occupied_pct: 'व्याप्त', available_pct: 'उपलब्ध' },
        beds_with_count: '{{count}} खाटा'
      },
      header: {
        greeting: { morning: 'शुभ प्रभात', afternoon: 'शुभ दुपार', evening: 'शुभ संध्याकाळ' },
        subtitle: 'तुमचा डॅशबोर्ड तयार आहे.'
      }
    },
  }
};

export default mr;
