const te = {
  translation: {
    nav: { 
      title: 'PG మేనేజర్', 
      notifications: 'నోటిఫికేషన్లు', 
      unread: '{{count}} చదవలేదు', 
      loading: 'లోడ్ అవుతోంది…', 
      close: 'మూసివేయి', 
      none: 'నోటిఫికేషన్లు లేవు', 
      refresh: 'రిఫ్రెష్', 
      more: 'మరింత', 
      profile: 'మీ ప్రొఫైల్', 
      settings: 'సెట్టింగ్స్', 
      sign_out: 'సైన్ అవుట్',
      user: 'వాడుకరి',
      filter_by_buildings: 'భవనాల ప్రకారం ఫిల్టర్ చేయండి',
      all_buildings: 'అన్ని భవనాలు',
      n_selected: '{{count}} ఎంపిక',
      select_all: 'అన్నీ ఎంచుకోండి',
      clear: 'క్లియర్' 
    },
    sidebar: { 
      dashboard: 'డాష్‌బోర్డ్', 
      buildings: 'భవనాలు', 
      tenants: 'కిరాయిదారులు', 
      income: 'ఆదాయం', 
      expenses: 'ఖర్చులు', 
      bookings: 'బుకింగ్స్', 
      payments: 'చెల్లింపులు', 
      messages: 'సందేశాలు', 
      settings: 'సెట్టింగ్స్', 
      reports: 'నివేదికలు', 
      staffs: 'సిబ్బంది' 
    },
    login: { 
      login_as: 'లాగిన్ అవ్వండి', 
      select_role: 'పాత్ర ఎంచుకోండి', 
      role_pg_admin: 'PG అడ్మిన్', 
      role_pg_staff: 'PG సిబ్బంది', 
      email: 'ఇమెయిల్ చిరునామా', 
      email_placeholder: 'మీ ఇమెయిల్ ఇవ్వండి', 
      password: 'పాస్వర్డ్', 
      password_placeholder: 'మీ పాస్వర్డ్ ఇవ్వండి', 
      remember_me: 'నన్ను గుర్తుంచుకో', 
      forgot_password: 'పాస్వర్డ్ మర్చిపోయారా?', 
      sign_in: 'సైన్ ఇన్', 
      signing_in: 'సైన్ ఇన్ అవుతోంది...', 
      no_account: 'ఖాతా లేదా?', 
      sign_up: 'సైన్ అప్', 
      success: 'లాగిన్ విజయవంతం! మళ్లిస్తాం...', 
      errors: { 
        select_role: 'దయచేసి పాత్రను ఎంచుకోండి', 
        email_required: 'ఇమెయిల్ అవసరం', 
        email_invalid: 'ఇమెయిల్ చెల్లదు', 
        password_required: 'పాస్వర్డ్ అవసరం', 
        failed: 'లాగిన్ విఫలమైంది. దయచేసి తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.' 
      } 
    },
    buildings: { 
      name: 'పేరు', 
      city: 'నగరం', 
      state: 'రాష్ట్రం', 
      type: 'రకం', 
      status: 'స్థితి', 
      active: 'సక్రియం', 
      inactive: 'నిష్క్రియం', 
      actions: 'చర్యలు', 
      list: 'జాబితా', 
      cards: 'కార్డులు', 
      overview: 'అవలోకనం',
      no_buildings: 'భవనాలు లేవు', 
      loading: 'భవనాలు లోడ్ అవుతున్నాయి...', 
      permission_denied: 'ఏ భవనాలనైనా చూడడానికి మీకు అనుమతి లేదు', 
      load_failed: 'భవనాలను లోడ్ చేయడంలో విఫలమైంది', 
      view_details: 'వివరాలు చూడండి', 
      address: 'చిరునామా:', 
      notes: 'గమనికలు:', 
      type_boys: 'బాయ్స్', 
      type_girls: 'గర్ల్స్', 
      type_coliving: 'కో-లివింగ్',
      building_with_id: 'భవనం {{id}}',
      title: 'భవనాలు',
      add_building: 'భవనం జోడించండి',
      edit_building_title: 'భవనం సవరించు: {{name}}',
      address_label: 'చిరునామా',
      notes_label: 'గమనికలు',
      back: 'వెనక్కి',
      view_on_maps: 'మ్యాప్స్‌లో చూడండి',
      open_in_maps: 'Google Maps లో తెరవండి',
      floors_label: 'అంతస్తులు',
      rooms_label: 'గదులు',
      beds_label: 'పడకలు',
      code: 'కోడ్',
      pincode: 'పిన్ కోడ్',
      manager: 'మేనేజర్',
      created: 'సృష్టించబడింది',
      updated: 'నవీకరించబడింది',
      not_found: 'భవనం కనబడలేదు.',
      updated_success: 'భవనం నవీకరించబడింది',
      property_type: 'ఆస్తి రకం',
      total_tenants: 'మొత్తం కిరాయిదారులు',
      pg_capacity: 'PG సామర్థ్యం',
      room_occupancy: 'గది ఆక్యుపెన్సీ',
      bed_occupancy: 'పడక ఆక్యుపెన్సీ',
      tooltip_occupied: '{{pct}}% ఆక్రమిత',
      tooltip_available: '{{pct}}% లభ్యం',
      tooltip_maintenance: '{{pct}}% నిర్వహణ',
      available: 'లభ్యం',
      occupied: 'ఆక్రమిత',
      reserved: 'రిజర్వ్',
      maintenance_short: 'మెయింట్.',
      action_edit: 'సవరించు',
      action_inactive_soft_deleted: 'నిష్క్రియం (సాఫ్ట్ డిలీట్)',
      action_soft_delete: 'సాఫ్ట్ డిలీట్',
      action_delete_permanently: 'శాశ్వతంగా తొలగించు',
      confirm_delete_title: 'భవనం తొలగించు',
      confirm_soft_delete_title: 'భవనం నిష్క్రియం చేయి',
      confirm_delete_message: 'ఇది "{{name}}" ను శాశ్వతంగా తొలగిస్తుంది. ఈ చర్యను తిరిగి తీసుకురాలేం.',
      confirm_soft_delete_message: '"{{name}}" ను నిష్క్రియం చేయాలా? తరువాత Active ను true గా చేసి పునరుద్ధరించవచ్చు.',
      cancel: 'రద్దు',
      soft_delete: 'సాఫ్ట్ డిలీట్',
      delete_hold_shift: 'తొలగించు (Shift నొక్కి)',
      permission_edit_deny: 'ఈ భవనాన్ని సవరించడానికి మీకు అనుమతి లేదు.',
      permission_delete_deny: 'ఈ భవనాన్ని తొలగించడానికి మీకు అనుమతి లేదు.',
      toasts_marked_inactive: 'భవనం నిష్క్రియం చేయబడింది',
      toasts_soft_delete_failed: 'సాఫ్ట్ డిలీట్ విఫలమైంది',
      toasts_deleted_permanently: 'భవనం శాశ్వతంగా తొలగించబడింది',
      toasts_delete_failed: 'తొలగింపు విఫలమైంది',
      toasts_hold_shift_to_confirm: 'శాశ్వత తొలగింపును ధృవీకరించడానికి Shift నొక్కి Delete నొక్కండి',
      stats_loading: 'గణాంకాలు లోడ్ అవుతున్నాయి…',
      stats_load_failed: 'గణాంకాలు లోడ్ చేయడంలో విఫలమైంది',
      placeholders: { name: 'భవనం పేరు ఇవ్వండి', address: 'చిరునామా ఇవ్వండి', city: 'నగరం ఇవ్వండి', state: 'రాష్ట్రం ఇవ్వండి', pincode: '6 అంకెలు', code: 'ఐచ్చికం', notes: 'అదనపు సమాచారం...' },
      errors: { owner_required: 'యజమాని అవసరం', name_required: 'పేరు అవసరం', address_required: 'చిరునామా అవసరం', city_required: 'నగరం అవసరం', state_required: 'రాష్ట్రం అవసరం', pincode_invalid: 'పిన్ కోడ్ 6 అంకెలు ఉండాలి', please_fix_fields: 'హైలైట్ చేసిన ఫీల్డ్స్ సరిచేయండి' },
      permissions: { no_permission_edit_buildings: 'భవనాలను సవరించడానికి మీకు అనుమతి లేదు', no_permission_add_buildings: 'భవనాలు జోడించడానికి మీకు అనుమతి లేదు', permission_denied_cannot_edit_building: 'అనుమతి నిరాకరించబడింది: ఈ భవనాన్ని సవరించలేరు.', permission_denied_cannot_add_buildings: 'అనుమతి నిరాకరించబడింది: భవనాలు జోడించలేరు.' },
      update: 'నవీకరించు',
      toasts: { building_updated: 'భవనం నవీకరించబడింది: {{name}}', building_created: 'భవనం సృష్టించబడింది: {{name}}' }
    },
    floors: {
      floor: 'అంతస్తు',
      floors: 'అంతస్తులు',
      building: 'భవనం',
      notes: 'గమనికలు',
      actions: 'చర్యలు',
      list: 'జాబితా',
      cards: 'కార్డులు',
      overview: 'అవలోకనం',
      no_floors: 'అంతస్తులు లభించలేదు',
      no_floors_for_building: 'ఈ భవనానికి అంతస్తులు లేవు',
      loading: 'అంతస్తులు లోడ్ అవుతున్నాయి...',
      permission_denied: 'అంతస్తులను చూడటానికి మీకు అనుమతి లేదు',
      permission_denied_for_building: 'ఈ భవనం యొక్క అంతస్తులను చూడటానికి మీకు అనుమతి లేదు',
      load_failed: 'అంతస్తులను లోడ్ చేయడంలో విఫలమైంది',
      view_details: 'వివరాలు చూడండి',
      rooms: 'గదులు',
      beds: 'పడకలు',
      capacity: 'సామర్థ్యం',
      room_occupancy: 'గది ఆక్యుపెన్సీ',
      bed_occupancy: 'పడక ఆక్యుపెన్సీ',
      tooltip_occupied: '{{pct}}% ఆక్రమించబడింది',
      tooltip_available: '{{pct}}% లభ్యం',
      floor_label_unknown: 'తెలియదు',
      floor_label_ground: 'గ్రౌండ్ ఫ్లోర్',
      floor_label_suffix: 'అంతస్తు',
      titles: {
        title: 'అంతస్తులు',
        add_floor: 'అంతస్తు జోడించండి',
        edit_floor_title: 'అంతస్తు సవరించు: {{name}}',
        edit_floor: 'అంతస్తు సవరించు'
      },
      select_building: 'భవనం ఎంచుకోండి',
      select_floor: 'అంతస్తు ఎంచుకోండి',
      errors: {
        building_required: 'భవనం అవసరం',
        number_required: 'సంఖ్య అవసరం',
        number_numeric: 'సంఖ్య అంకెల్లో ఉండాలి',
        number_range: 'సంఖ్య 0 మరియు 14 మధ్య ఉండాలి',
        duplicate_for_building: 'ఎంచుకున్న భవనానికి ఈ అంతస్తు ఇప్పటికే ఉంది.'
      },
      permissions: {
        reason_edit: 'ఈ భవనానికి అంతస్తును సవరించడానికి మీకు అనుమతి లేదు.',
        reason_add: 'అంతస్తును జోడించడానికి మీకు అనుమతి లేదు.',
        deny_edit: 'అనుమతి నిరాకరించబడింది: ఈ భవనానికి అంతస్తు సవరించలేరు.',
        deny_add: 'అనుమతి నిరాకరించబడింది: అంతస్తు జోడించలేరు.',
        deny_delete: 'అనుమతి నిరాకరించబడింది: ఈ భవనానికి అంతస్తు తొలగించలేరు.'
      },
      buttons: {
        save_changes: 'మార్పులను సేవ్ చేయి',
        create_floor: 'అంతస్తు సృష్టించండి'
      },
      toasts: {
        floor_updated: 'అంతస్తు నవీకరించబడింది: {{name}}',
        floor_created: 'అంతస్తు సృష్టించబడింది: {{name}}',
        created_success: 'అంతస్తు సృష్టించబడింది',
        updated_success: 'అంతస్తు నవీకరించబడింది'
      },
      save_failed: 'అంతస్తు సేవ్ చేయడంలో విఫలమైంది',
      action_edit: 'సవరించు',
      action_inactive_soft_deleted: 'నిష్క్రియం (సాఫ్ట్ డిలీట్)',
      action_soft_delete: 'సాఫ్ట్ డిలీట్',
      action_delete_permanently: 'శాశ్వతంగా తొలగించు',
      confirm_delete_title: 'అంతస్తును తొలగించు',
      confirm_soft_delete_title: 'అంతస్తును నిష్క్రియం చేయి',
      confirm_delete_message: '"{{name}}" శాశ్వతంగా తొలగించబడుతుంది. ఈ చర్యను తిరిగి తీసుకురాలేం.',
      confirm_soft_delete_message: '"{{name}}" ను నిష్క్రియం చేయాలా? తరువాత Active ను true గా చేసి పునరుద్ధరించవచ్చు.',
      cancel: 'రద్దు',
      soft_delete: 'సాఫ్ట్ డిలీట్',
      delete_hold_shift: 'తొలగించు (Shift నొక్కి)',
      toasts_marked_inactive: 'అంతస్తు నిష్క్రియం చేయబడింది',
      toasts_soft_delete_failed: 'సాఫ్ట్ డిలీట్ విఫలమైంది',
      toasts_deleted_permanently: 'అంతస్తు శాశ్వతంగా తొలగించబడింది',
      toasts_delete_failed: 'తొలగింపు విఫలమైంది',
      toasts_hold_shift_to_confirm: 'శాశ్వత తొలగింపును ధృవీకరించడానికి Shift నొక్కి Delete నొక్కండి',
    },
    rooms: {
      room: 'గది',
      rooms: 'గదులు',
      floor: 'అంతస్తు',
      type: 'రకం',
      capacity: 'సామర్థ్యం',
      rent: 'అద్దె',
      deposit: 'డిపాజిట్',
      available: 'లభ్యం',
      occupied: 'ఆక్రమిత',
      reserved: 'రిజర్వ్',
      maintenance: 'నిర్వహణ',
      yes: 'అవును',
      no: 'కాదు',
      actions: 'చర్యలు',
      list: 'జాబితా',
      cards: 'కార్డులు',
      no_rooms_for_floor: 'ఈ అంతస్తుకు గదులు లేవు',
      no_rooms: 'గదులు లభించలేదు',
      view_details: 'వివరాలు చూడండి',
      loading: 'గదులు లోడ్ అవుతున్నాయి...',
      permission_denied: 'గదులను చూడటానికి మీకు అనుమతి లేదు',
      load_failed: 'గదులను లోడ్ చేయడంలో విఫలమైంది',
      titles: {
        title: 'గదులు',
        add_room: 'గది జోడించండి',
        edit_room_title: 'గది సవరించు: {{name}}',
        edit_room: 'గది సవరించు'
      },
      labels: {
        number: 'గది సంఖ్య',
        room_type: 'గది రకం',
        monthly_rent: 'నెలసరి అద్దె',
        security_deposit: 'భద్రతా డిపాజిట్',
        notes: 'గమనికలు',
        active: 'సక్రియం',
        beds: 'పడకలు',
        bed_number: 'పడక సంఖ్య',
        status: 'స్థితి',
        auto_number: 'ఆటో సంఖ్య'
      },
      types: {
        single_sharing: 'సింగిల్ షేరింగ్',
        n_sharing: '{{n}}-షేరింగ్'
      },
      errors: {
        floor_required: 'అంతస్తు అవసరం',
        number_required: 'గది సంఖ్య అవసరం',
        room_type_required: 'గది రకం అవసరం',
        capacity_required: 'సామర్థ్యం అవసరం',
        bed_number_required: 'ప్రతి పడకకు సంఖ్య అవసరం',
        bed_number_unique: 'పడక సంఖ్యలు ప్రత్యేకంగా ఉండాలి',
        number_duplicate: 'గది సంఖ్య ఇప్పటికే ఉంది'
      },
      permissions: {
        reason_edit: 'ఈ భవనానికి గదిని సవరించడానికి మీకు అనుమతి లేదు.',
        reason_add: 'గది జోడించడానికి మీకు అనుమతి లేదు.',
        reason_delete: 'ఈ భవనానికి గదిని తొలగించడానికి మీకు అనుమతి లేదు.',
        deny_edit: 'అనుమతి నిరాకరించబడింది: ఈ భవనానికి గదిని సవరించలేరు.',
        deny_add: 'అనుమతి నిరాకరించబడింది: గది జోడించలేరు.',
        deny_delete: 'అనుమతి నిరాకరించబడింది: ఈ భవనానికి గదిని తొలగించలేరు.'
      },
      buttons: {
        save_changes: 'మార్పులను సేవ్ చేయి',
        create_room: 'గది సృష్టించండి'
      },
      toasts: {
        updated_success: 'గది నవీకరించబడింది',
        created_success: 'గది సృష్టించబడింది',
        marked_inactive: 'గది నిష్క్రియం చేయబడింది',
        soft_delete_failed: 'సాఫ్ట్ డిలీట్ విఫలమైంది',
        deleted_permanently: 'గది శాశ్వతంగా తొలగించబడింది',
        delete_failed: 'తొలగింపు విఫలమైంది',
        hold_shift_to_confirm: 'శాశ్వత తొలగింపును ధృవీకరించడానికి Shift నొక్కి Delete నొక్కండి'
      },
      save_failed: 'గది సేవ్ చేయడంలో విఫలమైంది',
      action_edit: 'సవరించు',
      action_inactive_soft_deleted: 'నిష్క్రియం (సాఫ్ట్ డిలీట్)',
      action_soft_delete: 'సాఫ్ట్ డిలీట్',
      action_delete_permanently: 'శాశ్వతంగా తొలగించు',
      confirm_delete_title: 'గదిని తొలగించు',
      confirm_soft_delete_title: 'గదిని నిష్క్రియం చేయి',
      confirm_delete_message: '"{{name}}" శాశ్వతంగా తొలగించబడుతుంది. ఈ చర్యను తిరిగి తీసుకురాలేం.',
      confirm_soft_delete_message: '"{{name}}" ను నిష్క్రియం చేయాలా? తరువాత Active ను true గా చేసి పునరుద్ధరించవచ్చు.',
      cancel: 'రద్దు',
      soft_delete: 'సాఫ్ట్ డిలీట్',
      delete_hold_shift: 'తొలగించు (Shift నొక్కి)'
    },
    beds: {
      title: 'మంచాలు',
      bed: 'మంచం',
      beds: 'మంచాలు',
      loading: 'మంచాలు లోడ్ అవుతున్నాయి...',
      no_beds: 'మంచాలు ఏవీ కనుగొనబడలేదు',
      no_beds_for_room: 'ఈ గదికి మంచాలు ఏవీ కనుగొనబడలేదు',
      view_details: 'వివరాలను వీక్షించండి',
      bed_with_number: 'మంచం {{n}}',
      bed_number: 'మంచం సంఖ్య',
      auto_number: 'స్వయంచాలక-సంఖ్య 1..N',
      available: 'అందుబాటులో ఉంది',
      occupied: 'అక్యుపై అయ్యింది',
      maintenance: 'మెయింటెనెన్స్',
      reserved: 'రిజర్వ్ చేయబడింది',
      status: 'స్థితి',
      rent: 'అద్దె',
      room: 'గది',
      building: 'భవనం',
      floor: 'అంతస్తు',
      tenant: 'అద్దెదారు',
      no_tenant: 'అద్దెదారు లేరు',
      notes: 'గమనికలు',
      confirm_delete: 'మీరు ఖచ్చితంగా ఈ మంచాన్ని తొలగించాలనుకుంటున్నారా?',
      delete_success: 'మంచం విజయవంతంగా తొలగించబడింది',
      delete_error: 'మంచాన్ని తొలగించడంలో లోపం',
      save_success: 'మంచం విజయవంతంగా సేవ్ అయింది',
      save_error: 'మంచాన్ని సేవ్ చేయడంలో లోపం',
      validation: {
        number_required: 'మంచం సంఖ్య అవసరం',
        number_unique: 'ఈ మంచం సంఖ్య ఇప్పటికే ఉంది',
        room_required: 'గదిని ఎంచుకోవాలి'
      },
      statuses: {
        available: 'అందుబాటులో ఉంది',
        occupied: 'అక్యుపై అయ్యింది',
        maintenance: 'మెయింటెనెన్స్',
        reserved: 'రిజర్వ్ చేయబడింది'
      },
      columns: {
        number: 'పడక #',
        status: 'స్థితి',
        rent: 'అద్దె'
      },
      toasts: {
        created: 'పడక విజయవంతంగా సృష్టించబడింది',
        updated: 'పడక విజయవంతంగా నవీకరించబడింది',
        updated_success: 'పడక విజయవంతంగా నవీకరించబడింది',
        checked_out_success: 'అద్దెదారు విజయవంతంగా చెక్-అవుట్ అయ్యారు',
        deleted_permanently: 'పడక శాశ్వతంగా తొలగించబడింది'
      },
      errors: {
        checkout_failed: 'చెక్-అవుట్ విఫలమైంది',
        delete_failed: 'తొలగింపు విఫలమైంది',
        save_failed: 'పడకను సేవ్ చేయడంలో విఫలమైంది',
        load_failed: 'పడకలను లోడ్ చేయడంలో విఫలమైంది'
      },
      actions: {
        add_bed: 'మంచం జోడించండి',
        edit_bed: 'మంచాన్ని సవరించండి',
        delete_bed: 'మంచాన్ని తొలగించండి',
        create_bed: 'మంచం సృష్టించు',
        check_out: 'చెక్-అవుట్',
        confirm_checkout: 'చెక్-అవుట్ నిర్ధారించండి'
      },
      dialogs: {
        delete_title: 'మంచాన్ని తొలగించు',
        checkout_title: 'అద్దెదారు చెక్-అవుట్',
        delete_description: '"{{label}}" శాశ్వతంగా తొలగించబడుతుంది. ఈ చర్యను తిరిగి తీసుకురాలేం.',
        checkout_description: 'ప్రస్తుత అద్దెదారుని "{{label}}" నుండి చెక్-అవుట్ చేయాలా? ఈ రోజు తేదీ వాస్తవ చెక్-అవుట్‌గా సెట్ చేయబడుతుంది.'
      },
      number_placeholder: 'ఉదా, B1, 1, A-01',
      rent_placeholder: 'ఉదా, 3500.00',
      notes_placeholder_maintenance: 'మెయింటెనెన్స్ కారణం (అవసరం)',
      notes_placeholder_optional: 'ఐచ్ఛిక గమనికలు',
      history: {
        title_for_label: '{{label}} కోసం మంచం చరిత్ర',
        description: 'ఈ మంచం కోసం ఇటీవలి బసలు మరియు బుకింగ్‌లు',
        occupied_no_history_hint: 'బుకింగ్ కారణంగా మంచం ఆక్యుపైడ్‌గా గుర్తించబడింది, కానీ ఇంకా స్టే చరిత్ర లేదు. మంచం వినియోగ చరిత్రను ట్రాక్ చేయడానికి స్టే సృష్టించండి.',
        no_history: 'చరిత్ర కనుగొనబడలేదు'
      },
    },
    settings: { 
      language: { 
        title: 'భాష', 
        subtitle: 'మీకు ఇష్టమైన యాప్ భాషను ఎంచుకోండి.', 
        label: 'భాష', 
        current: 'ప్రస్తుత' 
      },
      localization: {
        cancel: 'రద్దు'
      }
    },
    common: { 
      save: 'సేవ్',
      saving: 'సేవ్ అవుతోంది…',
      load_more: 'ఇంకా లోడ్ చేయి',
      actions: 'చర్యలు',
      edit: 'సవరించు',
      delete_permanently: 'శాశ్వతంగా తొలగించు',
      cancel: 'రద్దు',
      confirm: 'నిర్ధారించు',
      delete_hold_shift: 'తొలగించు (Shift నొక్కి)',
      hold_shift_to_confirm: 'శాశ్వత తొలగింపును ధృవీకరించడానికి Shift నొక్కి Delete నొక్కండి',
      date_ranges: {
        today: 'ఈ రోజు',
        yesterday: 'నిన్న',
        last7: 'గత 7 రోజులు',
        last15: 'గత 15 రోజులు',
        last30: 'గత 30 రోజులు',
        this_month: 'ఈ నెల',
        last_month: 'గత నెల',
        this_year: 'ఈ సంవత్సరం',
        last_year: 'గత సంవత్సరం',
        range: 'పరిధి'
      }
    },
    toasts: { 
      must_login: 'భాషను నవీకరించడానికి లాగిన్ అవ్వండి.', 
      language_saved: 'భాష అభిరుచి సేవ్ అయింది.', 
      save_failed: 'భాష సేవ్ కాలేదు.' 
    },
    dashboard: {
      bed_availability: {
        title: 'పడకల లభ్యత',
        view_all: 'అన్నీ చూడండి',
        search_placeholder: 'పడక, గది, భవనం వెతకండి...',
        available_beds: 'లభ్యపడే పడకలు',
        loading: 'లోడ్ అవుతోంది…',
        empty: 'ఎంపికకు లభ్యపడే పడకలు ఏవీ కనబడలేదు.',
        bed_fallback: 'పడక #{{id}}',
        room: 'గది',
        building: 'భవనం',
        available_badge: 'లభ్యం',
        view_more: 'ఇంకా {{count}} చూడండి',
        load_failed: 'లోడ్ విఫలమైంది'
      },
      cashflow: {
        title: 'నగదు ప్రవాహం',
        tabs: {
          overview: 'అవలోకనం',
          expenses: 'ఖర్చులు',
          weekdays: 'వారం రోజుల'
        },
        error: {
          title: 'లోడ్ చేయడంలో విఫలమైంది',
          retry: 'మళ్లీ ప్రయత్నించండి'
        },
        charts: {
          income_vs_expenses: 'ఆదాయం vs ఖర్చులు'
        },
        series: {
          income: 'ఆదాయం',
          expenses: 'ఖర్చులు'
        },
        kpis: {
          title: 'ప్రధాన మీట్రిక్స్',
          total_income: 'మొత్తం ఆదాయం',
          total_expenses: 'మొత్తం ఖర్చులు',
          average_net: 'సగటు నెట్'
        },
        expenses: {
          category_share: 'వర్గం వాటా'
        },
        table: {
          category: 'వర్గం',
          amount: 'మొత్తం',
          percentage: 'శాతం',
          total: 'మొత్తం'
        },
        weekdays: {
          title: 'వారం రోజుల వారీగా ఆదాయం vs ఖర్చులు'
        }
      },
      bookings_trend: {
        title: 'బుకింగ్స్',
        tabs: { overview: 'అవలోకనం', sources: 'మూలాలు', trends: 'ప్రవణతలు' },
        status_distribution: 'స్థితి పంపిణీ',
        count: 'ఎణ్ణం',
        key_metrics: 'ప్రధాన మీట్రిక్స్',
        total_bookings: 'మొత్తం బుకింగ్స్',
        total_revenue: 'మొత్తం ఆదాయం',
        booking_rate: 'బుకింగ్ శాతం',
        cancellation_rate: 'రద్దు శాతం',
        booking_sources_rate: 'బుకింగ్ మూలాల శాతం',
        source_details: 'మూల వివరాలు',
        source: 'మూలం',
        bookings: 'బుకింగ్స్',
        bookings_short: 'బుకింగ్స్',
        conv_short: 'కన్వ్',
        conversion_rate: 'మార్పిడి రేటు',
        market_share: 'మార్కెట్ వాటా',
        daily_booking_pattern: 'దైనందిన బుకింగ్ నమూనా',
        daily_bookings: 'దైనందిన బుకింగ్స్'
      },
      tenant_snapshot: {
        title: 'కిరాయిదారుల సారాంశం',
        view_all: 'అన్నీ చూడండి',
        total_tenants: 'మొత్తం కిరాయిదారులు',
        upcoming_checkins: 'రాబోయే చెక్-ఇన్‌లు',
        upcoming_checkouts: 'రాబోయే చెక్-అవుట్‌లు',
        selected_buildings: 'ఎంచుకున్న భవనాలు',
        recent_tenants: 'ఇటీవలి కిరాయిదారులు',
        open: 'తెరవండి',
        no_tenants: 'కిరాయిదారులు కనబడలేదు.',
        view_more: 'మరింత చూడండి'
      },
      occupancy: {
        title: 'ప్రత్యక్ష ఆక్యుపెన్సీ',
        occupied_chip: 'ఆక్రమిత',
        buildings_label: 'భవనాలు',
        all: 'అన్నీ',
        beds_considered: 'పరిశీలించిన పడకలు',
        empty: 'ఎంచుకున్న భవనాలకు పడకలు కనబడలేదు. ఆక్యుపెన్సీ చూడటానికి ఫిల్టర్ సరిచేయండి.',
        aria_overall: 'మొత్తం ఆక్యుపెన్సీ',
        legend: { occupied: 'ఆక్రమిత', reserved: 'రిజర్వ్', maintenance: 'నిర్వహణ', available: 'లభ్యం' },
        stats: { total: 'మొత్తం', occupied: 'ఆక్రమిత', reserved: 'రిజర్వ్', maintenance: 'నిర్వహణ', available: 'లభ్యం', occupied_pct: 'ఆక్రమిత', available_pct: 'లభ్యం' },
        beds_with_count: '{{count}} పడకలు'
      },
      header: {
        greeting: { morning: 'శుభోదయం', afternoon: 'శుభ మధ్యాహ్నం', evening: 'శుభ సాయంత్రం' }, 
        subtitle: 'మీ డ్యాష్‌బోర్డ్ సిద్ధంగా ఉంది.'
      }
    },
  }
};

export default te;
